# ==============================
# Base directories
# ==============================
input_dir: "input_dir"
output_dir: "./results"
platform: "droplet"  # micro well
Fastq_file_format: "merged"  # or "subdir"

# ==============================
# STAR genome build parameters
# ==============================
genome_dir: "./genome" # Output folder for the genome index preparation
fasta_file: "fasta"

# Genome indexing parameters (17.5)
genome_index_params:
  genomeChrBinNbits: 18
  genomeSAindexNbases: 14
  genomeSAsparseD: 1
  genomeSuffixLengthMax: -1
  genomeTransformType: None       # None | Haploid | Diploid
  genomeTransformVCF: null        # Path to VCF if genomeTransformType is Haploid/Diploid

# Splice junction parameters (17.6)
splice_junction_params:
  sjdbFileChrStartEnd: null       # Optional path(s) to files with genomic coordinates of introns
  sjdbGTFfile: ".gtf"
  sjdbGTFchrPrefix: ""
  sjdbGTFfeatureExon: "exon"
  sjdbGTFtagExonParentTranscript: "transcript_id"
  sjdbGTFtagExonParentGene: "gene_id"
  sjdbGTFtagExonParentGeneName: "gene_name"
  sjdbGTFtagExonParentGeneType: "gene_biotype"
  sjdbOverhang: 99                
  sjdbScore: 2
  sjdbInsertSave: "Basic"         # "Basic" or "All"

# ==============================
# STARsolo parameters for 10x
# ==============================
STARsolo_params_10x:
  soloType: "CB_UMI_Simple"
  soloCBstart: 1
  soloCBlen: 16
  soloUMIstart: 17
  soloUMIlen: 12
  soloCBwhitelist: "None"

# ==============================
# STARsolo parameters for DropSeq
# ==============================
STARsolo_params_DropSeq:
  soloType: "CB_UMI_Simple"
  soloCBstart: 1
  soloCBlen: 12        # DropSeq CB default is shorter (adjust if needed)
  soloUMIstart: 13
  soloUMIlen: 8
  soloCBwhitelist: "None"    # DropSeq has no whitelist

# ==============================
# STAR parameters
# ==============================
star_params:
  outSAMtype: "BAM SortedByCoordinate"
  outFilterMultimapNmax: 1
  twopassMode: "Basic"
  outSAMattributes: "NH HI AS nM MD"
  outSAMunmapped: "Within"
  outSAMmapqUnique: 60
  outFilterMismatchNoverLmax: 0.04
  alignSJoverhangMin: 8
  alignSJDBoverhangMin: 1

# ==============================
# Normalization + filtering parameters
# ==============================
HVG_selection: True # or False
number_top_genes: 2000
n_genes_by_counts_thres: 150
pct_counts_mt_thres: 10
total_counts_thres: 200
